# Generated by Django 5.2.4 on 2025-07-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
